fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
}


fragment GlobalParts on GlobalHeader {
  name
  color
  image {
    src
    alt
  }
  nav {
    href
    label
  }
  # Include other fields of GlobalHeader if necessary
}
